# Generated by Django 4.1.3 on 2022-11-20 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complete', models.BooleanField()),
                ('customer', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='pictures')),
                ('site', models.ForeignKey(default='0', on_delete=django.db.models.deletion.SET_DEFAULT, to='main.site')),
            ],
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='forms')),
                ('location', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('separator', models.CharField(max_length=200)),
                ('site', models.ForeignKey(default='0', on_delete=django.db.models.deletion.SET_DEFAULT, to='main.site')),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owned', models.BooleanField()),
                ('type', models.CharField(max_length=200)),
                ('unit_num', models.IntegerField()),
                ('mileage', models.IntegerField()),
                ('last_service', models.DateField()),
                ('last_inspection', models.DateField()),
                ('site', models.ForeignKey(default='0', on_delete=django.db.models.deletion.SET_DEFAULT, to='main.site')),
            ],
        ),
        migrations.CreateModel(
            name='Blueprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='blueprints')),
                ('site', models.ForeignKey(default='0', on_delete=django.db.models.deletion.SET_DEFAULT, to='main.site')),
            ],
        ),
    ]
