# Generated by Django 4.1.3 on 2022-11-20 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_navmenuitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='navmenuitem',
            name='dropdown',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
