# Generated by Django 4.1.3 on 2022-12-19 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_newuser_first_name_alter_newuser_last_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rectangle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side_ab', models.CharField(max_length=10)),
                ('side_ac', models.CharField(max_length=10)),
                ('side_bd', models.CharField(max_length=10)),
                ('side_cd', models.CharField(max_length=10)),
                ('diag_ad', models.CharField(max_length=10)),
                ('diag_bc', models.CharField(max_length=10)),
            ],
        ),
    ]
